/**
 * Roster image scanner — turns uploaded portraits into profile pages.
 *
 *   bun scripts/scan-roster-images.ts
 *
 * Drop a portrait at public/speakers/roster/<slug>.webp (the slug from the
 * roster, e.g. a-wess-mitchell) and re-run this. Every slug found here gets a
 * full profile page at /speakers/<slug>, and their roster row links to it.
 * Never hand-edit the generated file.
 */
import { existsSync, mkdirSync, readdirSync } from "node:fs";
import { format, resolveConfig } from "prettier";

const DIR = "public/speakers/roster";
if (!existsSync(DIR)) mkdirSync(DIR, { recursive: true });

const slugs = readdirSync(DIR)
  .filter((f) => f.endsWith(".webp"))
  .map((f) => f.slice(0, -".webp".length))
  .sort();

const out = `// GENERATED by scripts/scan-roster-images.ts — do not edit by hand.
// Roster speakers with an uploaded portrait at public/speakers/roster/<slug>.webp.
// Each slug here gets a profile page at /speakers/<slug>. Small on purpose:
// safe to import from client components.

export const rosterImageSlugs: readonly string[] = ${JSON.stringify(slugs, null, 2)};
`;

// Keep the generated file prettier-clean so lint stays green on sync PRs.
const GENERATED = "src/data/roster-images.generated.ts";
await Bun.write(
  GENERATED,
  await format(out, { ...(await resolveConfig(GENERATED)), filepath: GENERATED }),
);
console.log(`wrote src/data/roster-images.generated.ts (${slugs.length} portraits)`);
