/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForSpeakersRouteImport } from './routes/for-speakers'
import { Route as GetMatchedRouteImport } from './routes/get-matched'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as SpeakerFeesRouteImport } from './routes/speaker-fees'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as ForSpeakersIndexRouteImport } from './routes/for-speakers.index'
import { Route as SpeakersIndexRouteImport } from './routes/speakers.index'
import { Route as SpeakersSlugRouteImport } from './routes/speakers.$slug'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSpeakersRoute = ForSpeakersRouteImport.update({
  id: '/for-speakers',
  path: '/for-speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const GetMatchedRoute = GetMatchedRouteImport.update({
  id: '/get-matched',
  path: '/get-matched',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakerFeesRoute = SpeakerFeesRouteImport.update({
  id: '/speaker-fees',
  path: '/speaker-fees',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSpeakersIndexRoute = ForSpeakersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForSpeakersRoute,
} as any)
const SpeakersIndexRoute = SpeakersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpeakersRoute,
} as any)
const SpeakersSlugRoute = SpeakersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SpeakersRoute,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/for-speakers': typeof ForSpeakersRouteWithChildren
  '/get-matched': typeof GetMatchedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/speaker-fees': typeof SpeakerFeesRoute
  '/speakers': typeof SpeakersRouteWithChildren
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/for-speakers/': typeof ForSpeakersIndexRoute
  '/speakers/': typeof SpeakersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-matched': typeof GetMatchedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/speaker-fees': typeof SpeakerFeesRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/for-speakers': typeof ForSpeakersIndexRoute
  '/speakers': typeof SpeakersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/for-speakers': typeof ForSpeakersRouteWithChildren
  '/get-matched': typeof GetMatchedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/speaker-fees': typeof SpeakerFeesRoute
  '/speakers': typeof SpeakersRouteWithChildren
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/for-speakers/': typeof ForSpeakersIndexRoute
  '/speakers/': typeof SpeakersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/for-speakers'
    | '/get-matched'
    | '/how-it-works'
    | '/speaker-fees'
    | '/speakers'
    | '/speakers/$slug'
    | '/topics/$slug'
    | '/for-speakers/'
    | '/speakers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get-matched'
    | '/how-it-works'
    | '/speaker-fees'
    | '/speakers/$slug'
    | '/topics/$slug'
    | '/for-speakers'
    | '/speakers'
  id:
    | '__root__'
    | '/'
    | '/for-speakers'
    | '/get-matched'
    | '/how-it-works'
    | '/speaker-fees'
    | '/speakers'
    | '/speakers/$slug'
    | '/topics/$slug'
    | '/for-speakers/'
    | '/speakers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForSpeakersRoute: typeof ForSpeakersRouteWithChildren
  GetMatchedRoute: typeof GetMatchedRoute
  HowItWorksRoute: typeof HowItWorksRoute
  SpeakerFeesRoute: typeof SpeakerFeesRoute
  SpeakersRoute: typeof SpeakersRouteWithChildren
  TopicsSlugRoute: typeof TopicsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-speakers': {
      id: '/for-speakers'
      path: '/for-speakers'
      fullPath: '/for-speakers'
      preLoaderRoute: typeof ForSpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-matched': {
      id: '/get-matched'
      path: '/get-matched'
      fullPath: '/get-matched'
      preLoaderRoute: typeof GetMatchedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaker-fees': {
      id: '/speaker-fees'
      path: '/speaker-fees'
      fullPath: '/speaker-fees'
      preLoaderRoute: typeof SpeakerFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-speakers/': {
      id: '/for-speakers/'
      path: '/'
      fullPath: '/for-speakers/'
      preLoaderRoute: typeof ForSpeakersIndexRouteImport
      parentRoute: typeof ForSpeakersRoute
    }
    '/speakers/': {
      id: '/speakers/'
      path: '/'
      fullPath: '/speakers/'
      preLoaderRoute: typeof SpeakersIndexRouteImport
      parentRoute: typeof SpeakersRoute
    }
    '/speakers/$slug': {
      id: '/speakers/$slug'
      path: '/$slug'
      fullPath: '/speakers/$slug'
      preLoaderRoute: typeof SpeakersSlugRouteImport
      parentRoute: typeof SpeakersRoute
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ForSpeakersRouteChildren {
  ForSpeakersIndexRoute: typeof ForSpeakersIndexRoute
}

const ForSpeakersRouteChildren: ForSpeakersRouteChildren = {
  ForSpeakersIndexRoute: ForSpeakersIndexRoute,
}

const ForSpeakersRouteWithChildren = ForSpeakersRoute._addFileChildren(
  ForSpeakersRouteChildren,
)

interface SpeakersRouteChildren {
  SpeakersSlugRoute: typeof SpeakersSlugRoute
  SpeakersIndexRoute: typeof SpeakersIndexRoute
}

const SpeakersRouteChildren: SpeakersRouteChildren = {
  SpeakersSlugRoute: SpeakersSlugRoute,
  SpeakersIndexRoute: SpeakersIndexRoute,
}

const SpeakersRouteWithChildren = SpeakersRoute._addFileChildren(
  SpeakersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForSpeakersRoute: ForSpeakersRouteWithChildren,
  GetMatchedRoute: GetMatchedRoute,
  HowItWorksRoute: HowItWorksRoute,
  SpeakerFeesRoute: SpeakerFeesRoute,
  SpeakersRoute: SpeakersRouteWithChildren,
  TopicsSlugRoute: TopicsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
