/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as SpeakersIndexRouteImport } from './routes/speakers.index'
import { Route as SpeakersSlugRouteImport } from './routes/speakers.$slug'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersIndexRoute = SpeakersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpeakersRoute,
} as any)
const SpeakersSlugRoute = SpeakersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SpeakersRoute,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/speakers': typeof SpeakersRouteWithChildren
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/speakers/': typeof SpeakersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/speakers': typeof SpeakersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/speakers': typeof SpeakersRouteWithChildren
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/speakers/': typeof SpeakersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/speakers' | '/speakers/$slug' | '/topics/$slug' | '/speakers/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/speakers/$slug' | '/topics/$slug' | '/speakers'
  id:
    | '__root__'
    | '/'
    | '/speakers'
    | '/speakers/$slug'
    | '/topics/$slug'
    | '/speakers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpeakersRoute: typeof SpeakersRouteWithChildren
  TopicsSlugRoute: typeof TopicsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/': {
      id: '/speakers/'
      path: '/'
      fullPath: '/speakers/'
      preLoaderRoute: typeof SpeakersIndexRouteImport
      parentRoute: typeof SpeakersRoute
    }
    '/speakers/$slug': {
      id: '/speakers/$slug'
      path: '/$slug'
      fullPath: '/speakers/$slug'
      preLoaderRoute: typeof SpeakersSlugRouteImport
      parentRoute: typeof SpeakersRoute
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SpeakersRouteChildren {
  SpeakersSlugRoute: typeof SpeakersSlugRoute
  SpeakersIndexRoute: typeof SpeakersIndexRoute
}

const SpeakersRouteChildren: SpeakersRouteChildren = {
  SpeakersSlugRoute: SpeakersSlugRoute,
  SpeakersIndexRoute: SpeakersIndexRoute,
}

const SpeakersRouteWithChildren = SpeakersRoute._addFileChildren(
  SpeakersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpeakersRoute: SpeakersRouteWithChildren,
  TopicsSlugRoute: TopicsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
