// GENERATED by scripts/import-roster.ts — do not edit by hand.
// Small on purpose: safe to import from client components.

// Annotated as readonly string[] rather than `as const`: filter values arrive
// from URL search params as plain strings, so a literal union buys nothing and
// makes every lookup need a cast.

/** Category labels. `RosterEntry.c` holds indices into this array. */
export const rosterCategories: readonly string[] = [
  "Adventurers",
  "Advertising & Marketing",
  "After Dinner Speakers",
  "AI",
  "Authors",
  "Business",
  "Celebrity",
  "Creativity & Innovation",
  "Diversity & Inclusion",
  "Economy & Finance",
  "Education",
  "Environment & Climate Change",
  "Food & Wine",
  "Health, Lifestyle & Wellbeing",
  "Indigenous Speakers",
  "Inspirational",
  "Intergenerational Influencers",
  "Leadership",
  "Master of Ceremonies (MCs) & Hosts",
  "Media",
  "Mental Health & Wellness",
  "Military",
  "Motivational",
  "People & Culture",
  "Politics & Law",
  "Resilience",
  "Social Media & Networking",
  "Social Trends & Current Affairs",
  "Sport",
  "Storytelling",
  "Sustainability",
  "Team Building",
  "Technology, Future & Innovation",
  "Virtual",
  "World Affairs",
];

/** State / region labels. `RosterEntry.s` holds indices into this array. */
export const rosterStates: readonly string[] = [
  "ACT",
  "Australia (nationwide)",
  "International",
  "New Zealand",
  "NSW",
  "NT",
  "QLD",
  "SA",
  "TAS",
  "VIC",
  "WA",
];

/**
 * Roster size, so pages can quote a real figure without importing the rows.
 * Excludes the hand-written full profiles in ./speakers.
 */
export const ROSTER_COUNT = 2131;
