// GENERATED by scripts/scan-roster-images.ts — do not edit by hand.
// Roster speakers with an uploaded portrait at public/speakers/roster/<slug>.webp.
// Each slug here gets a profile page at /speakers/<slug>. Small on purpose:
// safe to import from client components.

export const rosterImageSlugs: readonly string[] = [];
