// GENERATED by scripts/build-speaker-portraits.ts — do not edit by hand.
// Regenerate with: bun run build:portraits --manifest-only
//
// Small on purpose: safe to import from client components. Maps the speakers that
// have an image in public/speakers/ to its path and kind, so a profile without
// one renders the hatch placeholder during SSR rather than a broken image.
//
// "plate" is a rendered monogram graphic from build-speaker-plates.ts. "photo"
// is a portrait — generated or supplied. They get different alt text.
//
// Roster portraits (public/speakers/roster/<slug>.webp, scanned into
// roster-images.generated.ts) resolve through the same functions as a
// fallback, so the full-profile page, the index gate and the cards all agree
// on what "has a portrait" means.

import { rosterImageSlugs } from "./roster-images.generated";

export type PortraitKind = "plate" | "photo";

const PORTRAITS: Readonly<Record<string, { src: string; kind: PortraitKind }>> = {
  "andres-molina": { src: "/speakers/andres-molina.webp", kind: "photo" },
  "daniel-abbott": { src: "/speakers/daniel-abbott.webp", kind: "photo" },
  "daniel-hsu": { src: "/speakers/daniel-hsu.webp", kind: "photo" },
  "dr-maya-ellison": { src: "/speakers/dr-maya-ellison.webp", kind: "photo" },
  "grace-oyelaran": { src: "/speakers/grace-oyelaran.webp", kind: "photo" },
  "helena-brandt": { src: "/speakers/helena-brandt.webp", kind: "photo" },
  "james-okoro": { src: "/speakers/james-okoro.webp", kind: "photo" },
  "michael-toure": { src: "/speakers/michael-toure.webp", kind: "photo" },
  "nina-castellan": { src: "/speakers/nina-castellan.webp", kind: "photo" },
  "omar-haddad": { src: "/speakers/omar-haddad.webp", kind: "photo" },
  "priya-raman": { src: "/speakers/priya-raman.webp", kind: "photo" },
  "robert-ainsley": { src: "/speakers/robert-ainsley.webp", kind: "photo" },
  "sarah-lindqvist": { src: "/speakers/sarah-lindqvist.webp", kind: "photo" },
};

const ROSTER_PORTRAITS: ReadonlySet<string> = new Set(rosterImageSlugs);

/** Public path to a speaker's image, or null when there is not one yet. */
export function portraitFor(slug: string): string | null {
  return PORTRAITS[slug]?.src ?? (ROSTER_PORTRAITS.has(slug) ? `/speakers/roster/${slug}.webp` : null);
}

export function portraitKind(slug: string): PortraitKind | null {
  return PORTRAITS[slug]?.kind ?? (ROSTER_PORTRAITS.has(slug) ? "photo" : null);
}

/**
 * Alt text for a speaker's image.
 *
 * A plate carries the name and role as artwork and always sits beside a heading
 * with the same name, so it is decorative and takes an empty alt rather than
 * making a screen reader announce the name twice. A photo is described, and says
 * it is generated: the curated profiles are placeholders whose faces belong to
 * nobody, and roster portraits are AI-generated headshots published under the
 * site's disclosure convention.
 */
export function portraitAlt(slug: string, name: string): string {
  const kind = portraitKind(slug);
  if (kind === "plate") return "";
  if (PORTRAITS[slug])
    return `Portrait of ${name}, keynote speaker (AI-generated placeholder image)`;
  return `AI-generated portrait of ${name}, keynote speaker`;
}

export const PORTRAIT_COUNT = 13;

/**
 * The slugs with a portrait, in one place: the portrait is the editorial
 * quality bar — it decides which profiles are indexed, listed in the sitemap
 * and offered in the enquiry dropdown.
 */
export const portraitSlugs: readonly string[] = [
  "andres-molina",
  "daniel-abbott",
  "daniel-hsu",
  "dr-maya-ellison",
  "grace-oyelaran",
  "helena-brandt",
  "james-okoro",
  "michael-toure",
  "nina-castellan",
  "omar-haddad",
  "priya-raman",
  "robert-ainsley",
  "sarah-lindqvist"
];
