// GENERATED by scripts/build-speaker-portraits.ts — do not edit by hand.
// Regenerate with: bun run build:portraits --manifest-only
//
// Small on purpose: safe to import from client components. Maps the speakers
// that have a portrait in public/speakers/ to its path, so a profile without one
// renders the hatch placeholder during SSR rather than a broken image.

const PORTRAITS: Readonly<Record<string, string>> = {};

/** Public path to a speaker's portrait, or null when there is not one yet. */
export function portraitFor(slug: string): string | null {
  return PORTRAITS[slug] ?? null;
}

/**
 * Alt text for a generated portrait. Says the image is generated, because these
 * twelve profiles are placeholders and the face belongs to nobody.
 */
export function portraitAlt(name: string): string {
  return `Portrait of ${name}, keynote speaker (AI-generated placeholder image)`;
}

export const PORTRAIT_COUNT = 0;
