// GENERATED by scripts/build-speaker-portraits.ts — do not edit by hand.
// Regenerate with: bun run build:portraits --manifest-only
//
// Small on purpose: safe to import from client components. Maps the speakers that
// have an image in public/speakers/ to its path and kind, so a profile without
// one renders the hatch placeholder during SSR rather than a broken image.
//
// "plate" is a rendered monogram graphic from build-speaker-plates.ts. "photo"
// is a portrait — generated or supplied. They get different alt text.

export type PortraitKind = "plate" | "photo";

const PORTRAITS: Readonly<Record<string, { src: string; kind: PortraitKind }>> = {
  "andres-molina": {
    src: "/speakers/andres-molina.plate.png",
    kind: "plate",
  },
  "daniel-hsu": {
    src: "/speakers/daniel-hsu.plate.png",
    kind: "plate",
  },
  "dr-maya-ellison": {
    src: "/speakers/dr-maya-ellison.plate.png",
    kind: "plate",
  },
  "grace-oyelaran": {
    src: "/speakers/grace-oyelaran.plate.png",
    kind: "plate",
  },
  "helena-brandt": {
    src: "/speakers/helena-brandt.plate.png",
    kind: "plate",
  },
  "james-okoro": {
    src: "/speakers/james-okoro.plate.png",
    kind: "plate",
  },
  "michael-toure": {
    src: "/speakers/michael-toure.plate.png",
    kind: "plate",
  },
  "nina-castellan": {
    src: "/speakers/nina-castellan.plate.png",
    kind: "plate",
  },
  "omar-haddad": {
    src: "/speakers/omar-haddad.plate.png",
    kind: "plate",
  },
  "priya-raman": {
    src: "/speakers/priya-raman.plate.png",
    kind: "plate",
  },
  "robert-ainsley": {
    src: "/speakers/robert-ainsley.plate.png",
    kind: "plate",
  },
  "sarah-lindqvist": {
    src: "/speakers/sarah-lindqvist.plate.png",
    kind: "plate",
  },
};

/** Public path to a speaker's image, or null when there is not one yet. */
export function portraitFor(slug: string): string | null {
  return PORTRAITS[slug]?.src ?? null;
}

export function portraitKind(slug: string): PortraitKind | null {
  return PORTRAITS[slug]?.kind ?? null;
}

/**
 * Alt text for a speaker's image.
 *
 * A plate carries the name and role as artwork and always sits beside a heading
 * with the same name, so it is decorative and takes an empty alt rather than
 * making a screen reader announce the name twice. A photo is described, and says
 * it is generated, because these twelve profiles are placeholders and the face
 * belongs to nobody.
 */
export function portraitAlt(slug: string, name: string): string {
  return portraitKind(slug) === "plate"
    ? ""
    : `Portrait of ${name}, keynote speaker (AI-generated placeholder image)`;
}

export const PORTRAIT_COUNT = 12;
